# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LetsGetWeather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LetsGetWeather
  pod 'GooglePlaces' 

  target 'LetsGetWeatherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LetsGetWeatherUITests' do
    # Pods for testing
  end

end
